[general]
# Folder path containing NSE bhav copies organized into folders by year
bhav_folder = "~/Documents/python/eod2_utils/src/NSE-reports/nseBhav/"
# Folder path containing NSE delivery reports organized into folders by year
delivery_folder = "~/Documents/python/eod2_utils/src/NSE-reports/nseDelivery/"
# Folder path containing NSE Indices reports organized into folders by year
indices_folder = "~/Documents/python/eod2_utils/src/NSE-reports/nseIndices/"
# Output folder
output_folder = "~/Documents/python/eod2_utils/src/data"
# Corporate actions folder in JSON format (downloaded from NSE)
actions_folder = "~/Documents/python/eod2_utils/src/actions_json"
actions_db = "~/Documents/python/eod2_utils/src/actions/db/main.db"

# Avoid changing dates in collate
# Udiff format started from 2024-07-08
[collate.indices]
start_date = 2012-02-19

[collate.market_breadth]
start_date = 2024-02-01

[collate.no_isin]
start_date = 1994-12-31
end_date = 2011-06-21

[collate.udiff]
start_date = 2024-07-07

[collate.with_isin]
start_date = 2011-06-21
end_date = 2024-07-07

[download.pr_bhav]
start_date = 2011-06-22
output_folder = "~/Documents/python/eod2_utils/src/PR_ZIP/"

# cleanup.py - Remove duplicate rows and outdated stocks with no new entries in last 365 days
# Also ensures dates are correctly sorted.
[cleanup]
remove_outdated = true
